spring.application.name=WebUser
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/humber_shopping
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
